// Locale tables for the updater's dialogs and notification (menu-item labels
// live in index.ts's tMain next to the other menu strings). Pure module: only
// @airy-office/i18n, no Electron.
import { createI18n, getUiLang } from '@airy-office/i18n'

/** keys use {version} placeholders consumed by createI18n's format() */
const tUpd = createI18n({
  zh: {
    updAvailableTitle: '发现新版本',
    updAvailableBody: 'Airy {version} 已发布。',
    updDownloadButton: '下载',
    updNotesButton: '查看更新说明',
    updLaterButton: '稍后再说',
    updReadyTitle: '更新已下载',
    updReadyBody: 'Airy {version} 已下载完成。现在安装，还是退出 Airy 时安装？',
    updInstallNow: '立即安装并重启',
    updInstallOnQuit: '退出时安装',
    updNotifyTitle: 'Airy 有新版本',
    updNotifyBody: 'Airy {version} 已发布。点击打开下载页面。',
    updManualTitle: 'Airy 更新',
    updManualBody: 'Airy 在 macOS 上不支持自动更新（未签名构建）。请从发布页面下载最新版本。',
    updManualButton: '打开发布页面',
  },
  en: {
    updAvailableTitle: 'Update Available',
    updAvailableBody: 'Airy {version} is available.',
    updDownloadButton: 'Download',
    updNotesButton: 'Release Notes',
    updLaterButton: 'Later',
    updReadyTitle: 'Update Downloaded',
    updReadyBody: 'Airy {version} has been downloaded. Install it now, or when Airy quits?',
    updInstallNow: 'Install and Restart',
    updInstallOnQuit: 'Install on Quit',
    updNotifyTitle: 'Airy Update Available',
    updNotifyBody: 'Airy {version} is available. Click to open the download page.',
    updManualTitle: 'Airy Updates',
    updManualBody:
      'Airy cannot update itself on macOS (unsigned builds). Download the latest version from the releases page.',
    updManualButton: 'Open Releases Page',
  },
  ja: {
    updAvailableTitle: '新しいバージョンがあります',
    updAvailableBody: 'Airy {version} が利用可能です。',
    updDownloadButton: 'ダウンロード',
    updNotesButton: 'リリースノート',
    updLaterButton: '後で',
    updReadyTitle: 'アップデートをダウンロードしました',
    updReadyBody:
      'Airy {version} のダウンロードが完了しました。今すぐインストールしますか？終了時にインストールしますか？',
    updInstallNow: '今すぐインストールして再起動',
    updInstallOnQuit: '終了時にインストール',
    updNotifyTitle: 'Airy のアップデートがあります',
    updNotifyBody: 'Airy {version} が利用可能です。クリックしてダウンロードページを開きます。',
    updManualTitle: 'Airy のアップデート',
    updManualBody:
      'Airy は macOS 上で自己更新できません（未署名ビルド）。最新版はリリースページからダウンロードしてください。',
    updManualButton: 'リリースページを開く',
  },
  ko: {
    updAvailableTitle: '업데이트 가능',
    updAvailableBody: 'Airy {version}을(를) 사용할 수 있습니다.',
    updDownloadButton: '다운로드',
    updNotesButton: '릴리스 노트',
    updLaterButton: '나중에',
    updReadyTitle: '업데이트 다운로드 완료',
    updReadyBody:
      'Airy {version} 다운로드가 완료되었습니다. 지금 설치하시겠습니까, 종료할 때 설치하시겠습니까?',
    updInstallNow: '지금 설치하고 다시 시작',
    updInstallOnQuit: '종료 시 설치',
    updNotifyTitle: 'Airy 업데이트 가능',
    updNotifyBody: 'Airy {version}을(를) 사용할 수 있습니다. 클릭하여 다운로드 페이지를 여세요.',
    updManualTitle: 'Airy 업데이트',
    updManualBody:
      'Airy는 macOS에서 자체 업데이트를 할 수 없습니다(서명되지 않은 빌드). 최신 버전은 릴리스 페이지에서 내려받으세요.',
    updManualButton: '릴리스 페이지 열기',
  },
  fr: {
    updAvailableTitle: 'Mise à jour disponible',
    updAvailableBody: 'Airy {version} est disponible.',
    updDownloadButton: 'Télécharger',
    updNotesButton: 'Notes de version',
    updLaterButton: 'Plus tard',
    updReadyTitle: 'Mise à jour téléchargée',
    updReadyBody:
      'Airy {version} a été téléchargé. Installer maintenant, ou à la fermeture d’Airy ?',
    updInstallNow: 'Installer et redémarrer',
    updInstallOnQuit: 'Installer à la fermeture',
    updNotifyTitle: 'Mise à jour Airy disponible',
    updNotifyBody: 'Airy {version} est disponible. Cliquez pour ouvrir la page de téléchargement.',
    updManualTitle: 'Mises à jour d’Airy',
    updManualBody:
      'Airy ne peut pas se mettre à jour sur macOS (builds non signées). Téléchargez la dernière version depuis la page des versions.',
    updManualButton: 'Ouvrir la page des versions',
  },
  de: {
    updAvailableTitle: 'Update verfügbar',
    updAvailableBody: 'Airy {version} ist verfügbar.',
    updDownloadButton: 'Herunterladen',
    updNotesButton: 'Versionshinweise',
    updLaterButton: 'Später',
    updReadyTitle: 'Update heruntergeladen',
    updReadyBody:
      'Airy {version} wurde heruntergeladen. Jetzt installieren oder beim Beenden von Airy?',
    updInstallNow: 'Installieren und neu starten',
    updInstallOnQuit: 'Beim Beenden installieren',
    updNotifyTitle: 'Airy-Update verfügbar',
    updNotifyBody: 'Airy {version} ist verfügbar. Klicken Sie, um die Download-Seite zu öffnen.',
    updManualTitle: 'Airy-Updates',
    updManualBody:
      'Airy kann sich unter macOS nicht selbst aktualisieren (unsignierte Builds). Laden Sie die neueste Version von der Releases-Seite herunter.',
    updManualButton: 'Releases-Seite öffnen',
  },
  es: {
    updAvailableTitle: 'Actualización disponible',
    updAvailableBody: 'Airy {version} está disponible.',
    updDownloadButton: 'Descargar',
    updNotesButton: 'Notas de la versión',
    updLaterButton: 'Más tarde',
    updReadyTitle: 'Actualización descargada',
    updReadyBody: 'Airy {version} se ha descargado. ¿Instalar ahora, o al salir de Airy?',
    updInstallNow: 'Instalar y reiniciar',
    updInstallOnQuit: 'Instalar al salir',
    updNotifyTitle: 'Actualización de Airy disponible',
    updNotifyBody: 'Airy {version} está disponible. Haga clic para abrir la página de descargas.',
    updManualTitle: 'Actualizaciones de Airy',
    updManualBody:
      'Airy no puede actualizarse solo en macOS (compilaciones sin firmar). Descargue la última versión desde la página de versiones.',
    updManualButton: 'Abrir la página de versiones',
  },
  pt: {
    updAvailableTitle: 'Atualização disponível',
    updAvailableBody: 'Airy {version} está disponível.',
    updDownloadButton: 'Baixar',
    updNotesButton: 'Notas da versão',
    updLaterButton: 'Mais tarde',
    updReadyTitle: 'Atualização baixada',
    updReadyBody: 'Airy {version} foi baixado. Instalar agora, ou quando o Airy for encerrado?',
    updInstallNow: 'Instalar e reiniciar',
    updInstallOnQuit: 'Instalar ao sair',
    updNotifyTitle: 'Atualização do Airy disponível',
    updNotifyBody: 'Airy {version} está disponível. Clique para abrir a página de download.',
    updManualTitle: 'Atualizações do Airy',
    updManualBody:
      'O Airy não pode se autoatualizar no macOS (compilações não assinadas). Baixe a versão mais recente na página de lançamentos.',
    updManualButton: 'Abrir a página de lançamentos',
  },
  it: {
    updAvailableTitle: 'Aggiornamento disponibile',
    updAvailableBody: 'Airy {version} è disponibile.',
    updDownloadButton: 'Scarica',
    updNotesButton: 'Note di versione',
    updLaterButton: 'Più tardi',
    updReadyTitle: 'Aggiornamento scaricato',
    updReadyBody: 'Airy {version} è stato scaricato. Installarlo adesso o all’uscita da Airy?',
    updInstallNow: 'Installa e riavvia',
    updInstallOnQuit: "Installa all'uscita",
    updNotifyTitle: 'Aggiornamento di Airy disponibile',
    updNotifyBody: 'Airy {version} è disponibile. Fai clic per aprire la pagina di download.',
    updManualTitle: 'Aggiornamenti di Airy',
    updManualBody:
      "Airy non può aggiornarsi da solo su macOS (build non firmate). Scarica l'ultima versione dalla pagina delle release.",
    updManualButton: 'Apri la pagina delle release',
  },
  ru: {
    updAvailableTitle: 'Доступно обновление',
    updAvailableBody: 'Доступна версия Airy {version}.',
    updDownloadButton: 'Скачать',
    updNotesButton: 'Примечания к версии',
    updLaterButton: 'Позже',
    updReadyTitle: 'Обновление скачано',
    updReadyBody: 'Airy {version} скачан. Установить сейчас или при выходе из Airy?',
    updInstallNow: 'Установить и перезапустить',
    updInstallOnQuit: 'Установить при выходе',
    updNotifyTitle: 'Доступно обновление Airy',
    updNotifyBody: 'Доступна версия Airy {version}. Нажмите, чтобы открыть страницу загрузки.',
    updManualTitle: 'Обновления Airy',
    updManualBody:
      'Airy не может обновлять сам себя в macOS (неподписанные сборки). Скачайте последнюю версию со страницы релизов.',
    updManualButton: 'Открыть страницу релизов',
  },
  cs: {
    updAvailableTitle: 'K dispozici je aktualizace',
    updAvailableBody: 'Airy {version} je k dispozici.',
    updDownloadButton: 'Stáhnout',
    updNotesButton: 'Poznámky k vydání',
    updLaterButton: 'Později',
    updReadyTitle: 'Aktualizace stažena',
    updReadyBody: 'Airy {version} byl stažen. Nainstalovat nyní, nebo při ukončení Airy?',
    updInstallNow: 'Nainstalovat a restartovat',
    updInstallOnQuit: 'Nainstalovat při ukončení',
    updNotifyTitle: 'K dispozici je aktualizace Airy',
    updNotifyBody: 'Airy {version} je k dispozici. Kliknutím otevřete stránku se stažením.',
    updManualTitle: 'Aktualizace Airy',
    updManualBody:
      'Airy se v systému macOS nemůže aktualizovat sám (nepodepsaná sestavení). Nejnovější verzi stáhněte ze stránky vydání.',
    updManualButton: 'Otevřít stránku vydání',
  },
  pl: {
    updAvailableTitle: 'Dostępna aktualizacja',
    updAvailableBody: 'Airy {version} jest dostępny.',
    updDownloadButton: 'Pobierz',
    updNotesButton: 'Informacje o wydaniu',
    updLaterButton: 'Później',
    updReadyTitle: 'Aktualizacja pobrana',
    updReadyBody: 'Airy {version} został pobrany. Zainstalować teraz, czy przy zamykaniu Airy?',
    updInstallNow: 'Zainstaluj i uruchom ponownie',
    updInstallOnQuit: 'Zainstaluj przy wyjściu',
    updNotifyTitle: 'Dostępna aktualizacja Airy',
    updNotifyBody: 'Airy {version} jest dostępny. Kliknij, aby otworzyć stronę pobierania.',
    updManualTitle: 'Aktualizacje Airy',
    updManualBody:
      'Airy nie może samodzielnie aktualizować się w systemie macOS (niepodpisane kompilacje). Pobierz najnowszą wersję ze strony wydań.',
    updManualButton: 'Otwórz stronę wydań',
  },
  nl: {
    updAvailableTitle: 'Update beschikbaar',
    updAvailableBody: 'Airy {version} is beschikbaar.',
    updDownloadButton: 'Downloaden',
    updNotesButton: 'Release-opmerkingen',
    updLaterButton: 'Later',
    updReadyTitle: 'Update gedownload',
    updReadyBody: 'Airy {version} is gedownload. Nu installeren, of bij het afsluiten van Airy?',
    updInstallNow: 'Installeren en herstarten',
    updInstallOnQuit: 'Installeren bij afsluiten',
    updNotifyTitle: 'Airy-update beschikbaar',
    updNotifyBody: 'Airy {version} is beschikbaar. Klik om de downloadpagina te openen.',
    updManualTitle: 'Airy-updates',
    updManualBody:
      'Airy kan zichzelf op macOS niet bijwerken (niet-ondertekende builds). Download de nieuwste versie van de releases-pagina.',
    updManualButton: 'Releases-pagina openen',
  },
  th: {
    updAvailableTitle: 'มีอัปเดตให้ใช้งาน',
    updAvailableBody: 'Airy {version} พร้อมให้ใช้งานแล้ว',
    updDownloadButton: 'ดาวน์โหลด',
    updNotesButton: 'บันทึกประจำรุ่น',
    updLaterButton: 'ภายหลัง',
    updReadyTitle: 'ดาวน์โหลดอัปเดตแล้ว',
    updReadyBody: 'ดาวน์โหลด Airy {version} เรียบร้อยแล้ว ติดตั้งตอนนี้หรือตอนปิด Airy?',
    updInstallNow: 'ติดตั้งและรีสตาร์ทเดี๋ยวนี้',
    updInstallOnQuit: 'ติดตั้งเมื่อปิดโปรแกรม',
    updNotifyTitle: 'มีอัปเดต Airy',
    updNotifyBody: 'Airy {version} พร้อมให้ใช้งานแล้ว คลิกเพื่อเปิดหน้าดาวน์โหลด',
    updManualTitle: 'อัปเดต Airy',
    updManualBody:
      'Airy อัปเดตตัวเองบน macOS ไม่ได้ (บิลด์ที่ไม่ได้ลงนาม) โปรดดาวน์โหลดเวอร์ชันล่าสุดจากหน้ารีลีส',
    updManualButton: 'เปิดหน้ารีลีส',
  },
  id: {
    updAvailableTitle: 'Pembaruan Tersedia',
    updAvailableBody: 'Airy {version} tersedia.',
    updDownloadButton: 'Unduh',
    updNotesButton: 'Catatan Rilis',
    updLaterButton: 'Nanti',
    updReadyTitle: 'Pembaruan Diunduh',
    updReadyBody: 'Airy {version} telah diunduh. Pasang sekarang, atau saat Airy ditutup?',
    updInstallNow: 'Pasang dan Mulai Ulang',
    updInstallOnQuit: 'Pasang saat Keluar',
    updNotifyTitle: 'Pembaruan Airy Tersedia',
    updNotifyBody: 'Airy {version} tersedia. Klik untuk membuka halaman unduhan.',
    updManualTitle: 'Pembaruan Airy',
    updManualBody:
      'Airy tidak dapat memperbarui dirinya sendiri di macOS (build tidak ditandatangani). Unduh versi terbaru dari halaman rilis.',
    updManualButton: 'Buka Halaman Rilis',
  },
  ms: {
    updAvailableTitle: 'Kemas Kini Tersedia',
    updAvailableBody: 'Airy {version} tersedia.',
    updDownloadButton: 'Muat Turun',
    updNotesButton: 'Nota Keluaran',
    updLaterButton: 'Kemudian',
    updReadyTitle: 'Kemas Kini Dimuat Turun',
    updReadyBody: 'Airy {version} telah dimuat turun. Pasang sekarang, atau ketika Airy ditutup?',
    updInstallNow: 'Pasang dan Mula Semula',
    updInstallOnQuit: 'Pasang ketika Keluar',
    updNotifyTitle: 'Kemas Kini Airy Tersedia',
    updNotifyBody: 'Airy {version} tersedia. Klik untuk membuka halaman muat turun.',
    updManualTitle: 'Kemas Kini Airy',
    updManualBody:
      'Airy tidak boleh mengemas kini sendiri di macOS (binaan tidak ditandatangani). Muat turun versi terkini dari halaman keluaran.',
    updManualButton: 'Buka Halaman Keluaran',
  },
  he: {
    updAvailableTitle: 'עדכון זמין',
    updAvailableBody: 'Airy {version} זמין.',
    updDownloadButton: 'הורדה',
    updNotesButton: 'הערות גרסה',
    updLaterButton: 'מאוחר יותר',
    updReadyTitle: 'העדכון הורד',
    updReadyBody: 'Airy {version} הורד. להתקין עכשיו, או ביציאה מ-Airy?',
    updInstallNow: 'התקן והפעל מחדש',
    updInstallOnQuit: 'התקן ביציאה',
    updNotifyTitle: 'עדכון Airy זמין',
    updNotifyBody: 'Airy {version} זמין. לחץ כדי לפתוח את דף ההורדה.',
    updManualTitle: 'עדכוני Airy',
    updManualBody:
      'Airy אינו יכול לעדכן את עצמו ב-macOS (בילדים לא חתומים). הורד את הגרסה החדשה מעמוד המהדורות.',
    updManualButton: 'פתח את עמוד המהדורות',
  },
  hi: {
    updAvailableTitle: 'अपडेट उपलब्ध',
    updAvailableBody: 'Airy {version} उपलब्ध है।',
    updDownloadButton: 'डाउनलोड',
    updNotesButton: 'रिलीज़ नोट्स',
    updLaterButton: 'बाद में',
    updReadyTitle: 'अपडेट डाउनलोड हो गया',
    updReadyBody: 'Airy {version} डाउनलोड हो गया है। अभी इंस्टॉल करें, या Airy बंद होने पर?',
    updInstallNow: 'इंस्टॉल करके फिर से शुरू करें',
    updInstallOnQuit: 'बंद होने पर इंस्टॉल करें',
    updNotifyTitle: 'Airy अपडेट उपलब्ध',
    updNotifyBody: 'Airy {version} उपलब्ध है। डाउनलोड पेज खोलने के लिए क्लिक करें।',
    updManualTitle: 'Airy अपडेट',
    updManualBody:
      'Airy macOS पर खुद को अपडेट नहीं कर सकता (अनसाइन्ड बिल्ड)। नवीनतम संस्करण रिलीज़ पेज से डाउनलोड करें।',
    updManualButton: 'रिलीज़ पेज खोलें',
  },
  ar: {
    updAvailableTitle: 'التحديث متاح',
    updAvailableBody: 'Airy {version} متاح.',
    updDownloadButton: 'تنزيل',
    updNotesButton: 'ملاحظات الإصدار',
    updLaterButton: 'لاحقًا',
    updReadyTitle: 'تم تنزيل التحديث',
    updReadyBody: 'تم تنزيل Airy {version}. هل تريد التثبيت الآن أم عند إغلاق Airy؟',
    updInstallNow: 'التثبيت وإعادة التشغيل',
    updInstallOnQuit: 'التثبيت عند الإغلاق',
    updNotifyTitle: 'تحديث Airy متاح',
    updNotifyBody: 'Airy {version} متاح. انقر لفتح صفحة التنزيل.',
    updManualTitle: 'تحديثات Airy',
    updManualBody:
      'لا يستطيع Airy تحديث نفسه على macOS (إصدارات غير موقّعة). نزّل أحدث إصدار من صفحة الإصدارات.',
    updManualButton: 'فتح صفحة الإصدارات',
  },
  'zh-TW': {
    updAvailableTitle: '發現新版本',
    updAvailableBody: 'Airy {version} 已推出。',
    updDownloadButton: '下載',
    updNotesButton: '查看更新說明',
    updLaterButton: '稍後再說',
    updReadyTitle: '更新已下載',
    updReadyBody: 'Airy {version} 已下載完成。現在安裝，還是結束 Airy 時安裝？',
    updInstallNow: '立即安裝並重新啟動',
    updInstallOnQuit: '結束時安裝',
    updNotifyTitle: 'Airy 有新版本',
    updNotifyBody: 'Airy {version} 已推出。點按以開啟下載頁面。',
    updManualTitle: 'Airy 更新',
    updManualBody: 'Airy 在 macOS 上不支援自動更新（未簽署建置）。請從發布頁面下載最新版本。',
    updManualButton: '打開發布頁面',
  },
})

/** translate an updater string in the persisted UI language */
export function updaterText(
  key: Parameters<typeof tUpd>[1],
  params?: Parameters<typeof tUpd>[2],
): string {
  return tUpd(getUiLang(), key, params)
}
