// Locale tables for the updater's dialogs and notification (menu-item labels
// live in index.ts's tMain next to the other menu strings). Pure module: only
// @airy-office/i18n, no Electron.
import { createI18n, getUiLang } from '@airy-office/i18n'

/** keys use {version} placeholders consumed by createI18n's format() */
const tUpd = createI18n({
  zh: {
    updAvailableTitle: '发现新版本',
    updAvailableBody: 'Airy {version} 已发布。',
    updDownloadButton: '下载',
    updNotesButton: '查看更新说明',
    updLaterButton: '稍后再说',
    updReadyTitle: '更新已下载',
    updReadyBody: 'Airy {version} 已下载完成。现在安装，还是退出 Airy 时安装？',
    updInstallNow: '立即安装并重启',
    updInstallOnQuit: '退出时安装',
    updNotifyTitle: 'Airy 有新版本',
    updNotifyBody: 'Airy {version} 已发布。点击打开下载页面。',
  },
  en: {
    updAvailableTitle: 'Update Available',
    updAvailableBody: 'Airy {version} is available.',
    updDownloadButton: 'Download',
    updNotesButton: 'Release Notes',
    updLaterButton: 'Later',
    updReadyTitle: 'Update Downloaded',
    updReadyBody: 'Airy {version} has been downloaded. Install it now, or when Airy quits?',
    updInstallNow: 'Install and Restart',
    updInstallOnQuit: 'Install on Quit',
    updNotifyTitle: 'Airy Update Available',
    updNotifyBody: 'Airy {version} is available. Click to open the download page.',
  },
  ja: {
    updAvailableTitle: '新しいバージョンがあります',
    updAvailableBody: 'Airy {version} が利用可能です。',
    updDownloadButton: 'ダウンロード',
    updNotesButton: 'リリースノート',
    updLaterButton: '後で',
    updReadyTitle: 'アップデートをダウンロードしました',
    updReadyBody:
      'Airy {version} のダウンロードが完了しました。今すぐインストールしますか？終了時にインストールしますか？',
    updInstallNow: '今すぐインストールして再起動',
    updInstallOnQuit: '終了時にインストール',
    updNotifyTitle: 'Airy のアップデートがあります',
    updNotifyBody: 'Airy {version} が利用可能です。クリックしてダウンロードページを開きます。',
  },
  ko: {
    updAvailableTitle: '업데이트 가능',
    updAvailableBody: 'Airy {version}을(를) 사용할 수 있습니다.',
    updDownloadButton: '다운로드',
    updNotesButton: '릴리스 노트',
    updLaterButton: '나중에',
    updReadyTitle: '업데이트 다운로드 완료',
    updReadyBody:
      'Airy {version} 다운로드가 완료되었습니다. 지금 설치하시겠습니까, 종료할 때 설치하시겠습니까?',
    updInstallNow: '지금 설치하고 다시 시작',
    updInstallOnQuit: '종료 시 설치',
    updNotifyTitle: 'Airy 업데이트 가능',
    updNotifyBody: 'Airy {version}을(를) 사용할 수 있습니다. 클릭하여 다운로드 페이지를 여세요.',
  },
  fr: {
    updAvailableTitle: 'Mise à jour disponible',
    updAvailableBody: 'Airy {version} est disponible.',
    updDownloadButton: 'Télécharger',
    updNotesButton: 'Notes de version',
    updLaterButton: 'Plus tard',
    updReadyTitle: 'Mise à jour téléchargée',
    updReadyBody:
      'Airy {version} a été téléchargé. Installer maintenant, ou à la fermeture d’Airy ?',
    updInstallNow: 'Installer et redémarrer',
    updInstallOnQuit: 'Installer à la fermeture',
    updNotifyTitle: 'Mise à jour Airy disponible',
    updNotifyBody: 'Airy {version} est disponible. Cliquez pour ouvrir la page de téléchargement.',
  },
  de: {
    updAvailableTitle: 'Update verfügbar',
    updAvailableBody: 'Airy {version} ist verfügbar.',
    updDownloadButton: 'Herunterladen',
    updNotesButton: 'Versionshinweise',
    updLaterButton: 'Später',
    updReadyTitle: 'Update heruntergeladen',
    updReadyBody:
      'Airy {version} wurde heruntergeladen. Jetzt installieren oder beim Beenden von Airy?',
    updInstallNow: 'Installieren und neu starten',
    updInstallOnQuit: 'Beim Beenden installieren',
    updNotifyTitle: 'Airy-Update verfügbar',
    updNotifyBody: 'Airy {version} ist verfügbar. Klicken Sie, um die Download-Seite zu öffnen.',
  },
  es: {
    updAvailableTitle: 'Actualización disponible',
    updAvailableBody: 'Airy {version} está disponible.',
    updDownloadButton: 'Descargar',
    updNotesButton: 'Notas de la versión',
    updLaterButton: 'Más tarde',
    updReadyTitle: 'Actualización descargada',
    updReadyBody: 'Airy {version} se ha descargado. ¿Instalar ahora, o al salir de Airy?',
    updInstallNow: 'Instalar y reiniciar',
    updInstallOnQuit: 'Instalar al salir',
    updNotifyTitle: 'Actualización de Airy disponible',
    updNotifyBody: 'Airy {version} está disponible. Haga clic para abrir la página de descargas.',
  },
  pt: {
    updAvailableTitle: 'Atualização disponível',
    updAvailableBody: 'Airy {version} está disponível.',
    updDownloadButton: 'Baixar',
    updNotesButton: 'Notas da versão',
    updLaterButton: 'Mais tarde',
    updReadyTitle: 'Atualização baixada',
    updReadyBody: 'Airy {version} foi baixado. Instalar agora, ou quando o Airy for encerrado?',
    updInstallNow: 'Instalar e reiniciar',
    updInstallOnQuit: 'Instalar ao sair',
    updNotifyTitle: 'Atualização do Airy disponível',
    updNotifyBody: 'Airy {version} está disponível. Clique para abrir a página de download.',
  },
  it: {
    updAvailableTitle: 'Aggiornamento disponibile',
    updAvailableBody: 'Airy {version} è disponibile.',
    updDownloadButton: 'Scarica',
    updNotesButton: 'Note di versione',
    updLaterButton: 'Più tardi',
    updReadyTitle: 'Aggiornamento scaricato',
    updReadyBody: 'Airy {version} è stato scaricato. Installarlo adesso o all’uscita da Airy?',
    updInstallNow: 'Installa e riavvia',
    updInstallOnQuit: "Installa all'uscita",
    updNotifyTitle: 'Aggiornamento di Airy disponibile',
    updNotifyBody: 'Airy {version} è disponibile. Fai clic per aprire la pagina di download.',
  },
  ru: {
    updAvailableTitle: 'Доступно обновление',
    updAvailableBody: 'Доступна версия Airy {version}.',
    updDownloadButton: 'Скачать',
    updNotesButton: 'Примечания к версии',
    updLaterButton: 'Позже',
    updReadyTitle: 'Обновление скачано',
    updReadyBody: 'Airy {version} скачан. Установить сейчас или при выходе из Airy?',
    updInstallNow: 'Установить и перезапустить',
    updInstallOnQuit: 'Установить при выходе',
    updNotifyTitle: 'Доступно обновление Airy',
    updNotifyBody: 'Доступна версия Airy {version}. Нажмите, чтобы открыть страницу загрузки.',
  },
  cs: {
    updAvailableTitle: 'K dispozici je aktualizace',
    updAvailableBody: 'Airy {version} je k dispozici.',
    updDownloadButton: 'Stáhnout',
    updNotesButton: 'Poznámky k vydání',
    updLaterButton: 'Později',
    updReadyTitle: 'Aktualizace stažena',
    updReadyBody: 'Airy {version} byl stažen. Nainstalovat nyní, nebo při ukončení Airy?',
    updInstallNow: 'Nainstalovat a restartovat',
    updInstallOnQuit: 'Nainstalovat při ukončení',
    updNotifyTitle: 'K dispozici je aktualizace Airy',
    updNotifyBody: 'Airy {version} je k dispozici. Kliknutím otevřete stránku se stažením.',
  },
  pl: {
    updAvailableTitle: 'Dostępna aktualizacja',
    updAvailableBody: 'Airy {version} jest dostępny.',
    updDownloadButton: 'Pobierz',
    updNotesButton: 'Informacje o wydaniu',
    updLaterButton: 'Później',
    updReadyTitle: 'Aktualizacja pobrana',
    updReadyBody: 'Airy {version} został pobrany. Zainstalować teraz, czy przy zamykaniu Airy?',
    updInstallNow: 'Zainstaluj i uruchom ponownie',
    updInstallOnQuit: 'Zainstaluj przy wyjściu',
    updNotifyTitle: 'Dostępna aktualizacja Airy',
    updNotifyBody: 'Airy {version} jest dostępny. Kliknij, aby otworzyć stronę pobierania.',
  },
  nl: {
    updAvailableTitle: 'Update beschikbaar',
    updAvailableBody: 'Airy {version} is beschikbaar.',
    updDownloadButton: 'Downloaden',
    updNotesButton: 'Release-opmerkingen',
    updLaterButton: 'Later',
    updReadyTitle: 'Update gedownload',
    updReadyBody: 'Airy {version} is gedownload. Nu installeren, of bij het afsluiten van Airy?',
    updInstallNow: 'Installeren en herstarten',
    updInstallOnQuit: 'Installeren bij afsluiten',
    updNotifyTitle: 'Airy-update beschikbaar',
    updNotifyBody: 'Airy {version} is beschikbaar. Klik om de downloadpagina te openen.',
  },
  th: {
    updAvailableTitle: 'มีอัปเดตให้ใช้งาน',
    updAvailableBody: 'Airy {version} พร้อมให้ใช้งานแล้ว',
    updDownloadButton: 'ดาวน์โหลด',
    updNotesButton: 'บันทึกประจำรุ่น',
    updLaterButton: 'ภายหลัง',
    updReadyTitle: 'ดาวน์โหลดอัปเดตแล้ว',
    updReadyBody: 'ดาวน์โหลด Airy {version} เรียบร้อยแล้ว ติดตั้งตอนนี้หรือตอนปิด Airy?',
    updInstallNow: 'ติดตั้งและรีสตาร์ทเดี๋ยวนี้',
    updInstallOnQuit: 'ติดตั้งเมื่อปิดโปรแกรม',
    updNotifyTitle: 'มีอัปเดต Airy',
    updNotifyBody: 'Airy {version} พร้อมให้ใช้งานแล้ว คลิกเพื่อเปิดหน้าดาวน์โหลด',
  },
  id: {
    updAvailableTitle: 'Pembaruan Tersedia',
    updAvailableBody: 'Airy {version} tersedia.',
    updDownloadButton: 'Unduh',
    updNotesButton: 'Catatan Rilis',
    updLaterButton: 'Nanti',
    updReadyTitle: 'Pembaruan Diunduh',
    updReadyBody: 'Airy {version} telah diunduh. Pasang sekarang, atau saat Airy ditutup?',
    updInstallNow: 'Pasang dan Mulai Ulang',
    updInstallOnQuit: 'Pasang saat Keluar',
    updNotifyTitle: 'Pembaruan Airy Tersedia',
    updNotifyBody: 'Airy {version} tersedia. Klik untuk membuka halaman unduhan.',
  },
  ms: {
    updAvailableTitle: 'Kemas Kini Tersedia',
    updAvailableBody: 'Airy {version} tersedia.',
    updDownloadButton: 'Muat Turun',
    updNotesButton: 'Nota Keluaran',
    updLaterButton: 'Kemudian',
    updReadyTitle: 'Kemas Kini Dimuat Turun',
    updReadyBody: 'Airy {version} telah dimuat turun. Pasang sekarang, atau ketika Airy ditutup?',
    updInstallNow: 'Pasang dan Mula Semula',
    updInstallOnQuit: 'Pasang ketika Keluar',
    updNotifyTitle: 'Kemas Kini Airy Tersedia',
    updNotifyBody: 'Airy {version} tersedia. Klik untuk membuka halaman muat turun.',
  },
  he: {
    updAvailableTitle: 'עדכון זמין',
    updAvailableBody: 'Airy {version} זמין.',
    updDownloadButton: 'הורדה',
    updNotesButton: 'הערות גרסה',
    updLaterButton: 'מאוחר יותר',
    updReadyTitle: 'העדכון הורד',
    updReadyBody: 'Airy {version} הורד. להתקין עכשיו, או ביציאה מ-Airy?',
    updInstallNow: 'התקן והפעל מחדש',
    updInstallOnQuit: 'התקן ביציאה',
    updNotifyTitle: 'עדכון Airy זמין',
    updNotifyBody: 'Airy {version} זמין. לחץ כדי לפתוח את דף ההורדה.',
  },
  hi: {
    updAvailableTitle: 'अपडेट उपलब्ध',
    updAvailableBody: 'Airy {version} उपलब्ध है।',
    updDownloadButton: 'डाउनलोड',
    updNotesButton: 'रिलीज़ नोट्स',
    updLaterButton: 'बाद में',
    updReadyTitle: 'अपडेट डाउनलोड हो गया',
    updReadyBody: 'Airy {version} डाउनलोड हो गया है। अभी इंस्टॉल करें, या Airy बंद होने पर?',
    updInstallNow: 'इंस्टॉल करके फिर से शुरू करें',
    updInstallOnQuit: 'बंद होने पर इंस्टॉल करें',
    updNotifyTitle: 'Airy अपडेट उपलब्ध',
    updNotifyBody: 'Airy {version} उपलब्ध है। डाउनलोड पेज खोलने के लिए क्लिक करें।',
  },
  ar: {
    updAvailableTitle: 'التحديث متاح',
    updAvailableBody: 'Airy {version} متاح.',
    updDownloadButton: 'تنزيل',
    updNotesButton: 'ملاحظات الإصدار',
    updLaterButton: 'لاحقًا',
    updReadyTitle: 'تم تنزيل التحديث',
    updReadyBody: 'تم تنزيل Airy {version}. هل تريد التثبيت الآن أم عند إغلاق Airy؟',
    updInstallNow: 'التثبيت وإعادة التشغيل',
    updInstallOnQuit: 'التثبيت عند الإغلاق',
    updNotifyTitle: 'تحديث Airy متاح',
    updNotifyBody: 'Airy {version} متاح. انقر لفتح صفحة التنزيل.',
  },
  'zh-TW': {
    updAvailableTitle: '發現新版本',
    updAvailableBody: 'Airy {version} 已推出。',
    updDownloadButton: '下載',
    updNotesButton: '查看更新說明',
    updLaterButton: '稍後再說',
    updReadyTitle: '更新已下載',
    updReadyBody: 'Airy {version} 已下載完成。現在安裝，還是結束 Airy 時安裝？',
    updInstallNow: '立即安裝並重新啟動',
    updInstallOnQuit: '結束時安裝',
    updNotifyTitle: 'Airy 有新版本',
    updNotifyBody: 'Airy {version} 已推出。點按以開啟下載頁面。',
  },
})

/** translate an updater string in the persisted UI language */
export function updaterText(
  key: Parameters<typeof tUpd>[1],
  params?: Parameters<typeof tUpd>[2],
): string {
  return tUpd(getUiLang(), key, params)
}
